# Generated by Django 5.2.4 on 2026-09-03 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'avatar_categories',
            },
        ),
        migrations.CreateModel(
            name='AvatarCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('base_image_url', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'avatar_characters',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='CompanionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'companion_activities',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=150, null=True)),
                ('icon_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('order_index', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.parent')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('icon_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('intro_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('grade_level', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.subject')),
            ],
            options={
                'db_table': 'topics',
                'unique_together': {('subject', 'grade_level', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.TextField()),
                ('render_asset_url', models.TextField(blank=True, null=True)),
                ('unlock_type', models.CharField(choices=[('free', 'free'), ('achievement', 'achievement'), ('premium', 'premium')], default='free', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.avatarcategory')),
            ],
            options={
                'db_table': 'avatar_items',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeOpponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('avatar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=20)),
                ('ai_profile', models.JSONField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='api.challenge')),
            ],
            options={
                'db_table': 'challenge_opponents',
            },
        ),
        migrations.CreateModel(
            name='StudentStat',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='api.student')),
                ('day_streak', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_stats',
            },
        ),
        migrations.CreateModel(
            name='NovaInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nova_interactions', to='api.student')),
            ],
            options={
                'db_table': 'nova_interactions',
            },
        ),
        migrations.CreateModel(
            name='MissionRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_recommendations', to='api.student')),
            ],
            options={
                'db_table': 'mission_recommendations',
            },
        ),
        migrations.CreateModel(
            name='ChallengeBattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('preview', 'preview'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='preview', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('win', 'win'), ('loss', 'loss'), ('draw', 'draw')], max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challengeopponent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_battles', to='api.student')),
            ],
            options={
                'db_table': 'challenge_battles',
            },
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('data', models.JSONField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.student')),
            ],
            options={
                'db_table': 'student_cards',
            },
        ),
        migrations.CreateModel(
            name='StudentCompanionActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companionactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_logs', to='api.student')),
            ],
            options={
                'db_table': 'student_companion_activity_log',
            },
        ),
        migrations.AddField(
            model_name='companionactivity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('abandoned', 'abandoned')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='api.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
            options={
                'db_table': 'test_attempts',
            },
        ),
        migrations.CreateModel(
            name='ExtraLearningRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mission')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.testattempt')),
            ],
            options={
                'db_table': 'extra_learning_recommendations',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'mcq'), ('true_false', 'true_false'), ('short_answer', 'short_answer')], default='mcq', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test')),
            ],
            options={
                'db_table': 'test_questions',
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('answer', 'answer'), ('hint', 'hint'), ('retry', 'retry'), ('explanation', 'explanation'), ('read_aloud', 'read_aloud'), ('skip', 'skip')], max_length=30)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('hint_count', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('help_requested', models.BooleanField(default=False)),
                ('nova_intervention_used', models.BooleanField(default=False)),
                ('confidence_before', models.SmallIntegerField(blank=True, null=True)),
                ('confidence_after', models.SmallIntegerField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mission')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='api.student')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testquestion')),
            ],
            options={
                'db_table': 'learning_events',
            },
        ),
        migrations.CreateModel(
            name='TopicJourneyMeta',
            fields=[
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='journey_meta', serialize=False, to='api.topic')),
                ('world_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=150, null=True)),
                ('map_x', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('map_y', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('icon_asset', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_journey_meta',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.topic'),
        ),
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.topic'),
        ),
        migrations.AddField(
            model_name='mission',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.topic'),
        ),
        migrations.CreateModel(
            name='JourneyMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('order_index', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic')),
            ],
            options={
                'db_table': 'journey_milestones',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic'),
        ),
        migrations.CreateModel(
            name='TopicTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_key', models.CharField(choices=[('school_syllabus', 'School Syllabus'), ('kidsverse_plus', 'Kidsverse Plus'), ('competition_edge', 'Competition Edge')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('order_index', models.IntegerField(default=0)),
                ('required_plan', models.CharField(choices=[('free', 'free'), ('plus', 'plus')], default='free', max_length=30)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='api.topic')),
            ],
            options={
                'db_table': 'topic_tiers',
                'unique_together': {('topic', 'tier_key')},
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.topictier'),
        ),
        migrations.CreateModel(
            name='MissionSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.mission')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'mission_skills',
                'unique_together': {('mission', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_mastery', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('prerequisite_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_skills', to='api.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='api.skill')),
            ],
            options={
                'db_table': 'skill_prerequisites',
                'unique_together': {('skill', 'prerequisite_skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentAvatar',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='avatar', serialize=False, to='api.student')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.avataritem')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.avatarcharacter')),
                ('hair_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.avataritem')),
                ('outfit_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.avataritem')),
            ],
            options={
                'db_table': 'student_avatars',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=50)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='api.student')),
            ],
            options={
                'db_table': 'onboarding_steps',
                'unique_together': {('student', 'step_key')},
            },
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='locked', max_length=20)),
                ('stars', models.SmallIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to='api.student')),
            ],
            options={
                'db_table': 'mission_progress',
                'unique_together': {('student', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='StudentAvatarUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('default', 'default'), ('achievement', 'achievement'), ('challenge_reward', 'challenge_reward'), ('premium', 'premium')], default='default', max_length=30)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.avataritem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_unlocks', to='api.student')),
            ],
            options={
                'db_table': 'student_avatar_unlocks',
                'unique_together': {('student', 'item')},
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to='api.student')),
            ],
            options={
                'db_table': 'student_goals',
                'unique_together': {('student', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='api.student')),
            ],
            options={
                'db_table': 'student_interests',
                'unique_together': {('student', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='StudentJourneyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked'), ('completed', 'completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journeymilestone')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_progress', to='api.student')),
            ],
            options={
                'db_table': 'student_journey_progress',
                'unique_together': {('student', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkillMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('independence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('retention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_state', models.CharField(choices=[('not_started', 'not_started'), ('learning', 'learning'), ('secure', 'secure'), ('review_due', 'review_due')], default='not_started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to='api.student')),
            ],
            options={
                'db_table': 'student_skill_mastery',
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('default', 'default'), ('achievement', 'achievement'), ('plan_upgrade', 'plan_upgrade'), ('parent_action', 'parent_action')], default='default', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unlocks', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'db_table': 'student_subject_unlocks',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGradeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=20)),
                ('is_unlocked_default', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_availabilities', to='api.subject')),
            ],
            options={
                'db_table': 'subject_grade_availability',
                'unique_together': {('subject', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='TestAttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testquestion')),
            ],
            options={
                'db_table': 'test_attempt_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestionSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.testquestion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'test_question_skills',
                'unique_together': {('question', 'skill')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('topic', 'slug')},
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked'), ('current', 'current'), ('completed', 'completed')], default='locked', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='api.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
            options={
                'db_table': 'student_topic_progress',
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('topic', 'skill_key')},
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('topic', 'slug')},
        ),
    ]
