# Generated by Django 5.2.4 on 2026-09-10 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='board',
            field=models.CharField(default='CBSE', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'board', 'grade_level', 'slug')},
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('learning_objective', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='api.topic')),
            ],
            options={
                'db_table': 'concepts',
                'unique_together': {('topic', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.concept'),
        ),
        migrations.CreateModel(
            name='ConceptPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='Everyday Life', max_length=100)),
                ('content_type', models.CharField(default='concept_package', max_length=50)),
                ('teaching_method', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('nova_script', models.TextField(blank=True, null=True)),
                ('nova_feedback', models.TextField(blank=True, null=True)),
                ('check_for_understanding', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.concept')),
            ],
            options={
                'db_table': 'concept_packages',
                'unique_together': {('concept', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='ConceptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('cfu', 'Check for Understanding'), ('test', 'Test Question'), ('battle', 'Battle Question'), ('challenge', 'Challenge Question')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('marks_or_xp', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('nova_feedback', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.conceptpackage')),
            ],
            options={
                'db_table': 'concept_questions',
            },
        ),
    ]
