# Generated by Django 5.2.4 on 2026-09-12 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_topic_unique_together_topic_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.concept'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.conceptpackage'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BattleQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(default='Hard', max_length=20)),
                ('xp', models.IntegerField(default=20)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_questions', to='api.concept')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_questions', to='api.conceptpackage')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_questions', to='api.topic')),
            ],
            options={
                'db_table': 'battle_questions',
            },
        ),
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(default='Hard', max_length=20)),
                ('xp', models.IntegerField(default=35)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('nova_feedback', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.challenge')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='api.concept')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='api.conceptpackage')),
            ],
            options={
                'db_table': 'challenge_questions',
            },
        ),
        migrations.CreateModel(
            name='ConceptTestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('marks', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_one_time', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='api.concept')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='api.conceptpackage')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_test_questions', to='api.topic')),
            ],
            options={
                'db_table': 'concept_test_questions',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('board', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculums',
                'unique_together': {('board', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='curricula',
            field=models.ManyToManyField(blank=True, related_name='curriculum_subjects', to='api.curriculum'),
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.curriculum'),
        ),
        migrations.AddField(
            model_name='topic',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.curriculum'),
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teaching_method', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('nova_script', models.TextField(blank=True, null=True)),
                ('nova_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_contents', to='api.concept')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content', to='api.conceptpackage')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_contents', to='api.theme')),
            ],
            options={
                'db_table': 'learning_contents',
            },
        ),
        migrations.CreateModel(
            name='CheckForUnderstandingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfu_questions', to='api.conceptpackage')),
                ('learning_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfu_questions', to='api.learningcontent')),
            ],
            options={
                'db_table': 'check_for_understanding_questions',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='concepts', through='api.ConceptPackage', to='api.theme'),
        ),
        migrations.AlterField(
            model_name='conceptpackage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.theme'),
        ),
    ]
