# Generated by Django 5.2.4 on 2026-09-26 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_theme_challenge_concept_challenge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptpackage',
            name='learn_before_test',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='learn_before_test',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LearnBeforeTestStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('teaching_text', models.TextField(blank=True, null=True)),
                ('key_idea', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('nova_script', models.TextField(blank=True, null=True)),
                ('mini_question', models.JSONField(blank=True, default=dict)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn_steps', to='api.concept')),
                ('learning_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn_steps', to='api.learningcontent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_steps', to='api.conceptpackage')),
            ],
            options={
                'db_table': 'learn_before_test_steps',
                'ordering': ['order_index'],
            },
        ),
    ]
