# Generated by Django 5.2.4 on 2026-09-27

import django.db.models.deletion
import uuid
from django.db import migrations, models


def link_existing_curriculums(apps, schema_editor):
    Curriculum = apps.get_model('api', 'Curriculum')
    Student = apps.get_model('api', 'Student')
    Topic = apps.get_model('api', 'Topic')

    for topic in Topic.objects.filter(curriculum__isnull=True).select_related('subject'):
        curriculum, _ = Curriculum.objects.get_or_create(
            board=topic.board,
            grade=topic.grade_level,
            defaults={
                'name': f'{topic.board} - {topic.grade_level}',
                'code': f'{topic.board.lower()}-{topic.grade_level.lower()}'.replace(' ', '-'),
            },
        )
        topic.curriculum = curriculum
        topic.save(update_fields=['curriculum'])
        topic.subject.curricula.add(curriculum)

    for student in Student.objects.filter(curriculum__isnull=True).exclude(board__isnull=True).exclude(grade__isnull=True):
        curriculum = Curriculum.objects.filter(board__iexact=student.board, grade__iexact=student.grade).first()
        if curriculum:
            student.curriculum = curriculum
            student.save(update_fields=['curriculum'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conceptpackage_learn_before_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBreakPass',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='break_passes', serialize=False, to='api.student')),
                ('available_count', models.PositiveIntegerField(default=3)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'student_break_passes'},
        ),
        migrations.CreateModel(
            name='StudentSettings',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='api.student')),
                ('values', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'student_settings'},
        ),
        migrations.AddField(
            model_name='parent',
            name='pin_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.curriculum'),
        ),
        migrations.CreateModel(
            name='ParentVerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to='api.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_verification_challenges', to='api.student')),
            ],
            options={'db_table': 'parent_verification_challenges'},
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='api.parent')),
            ],
            options={'db_table': 'password_reset_requests'},
        ),
        migrations.RunPython(link_existing_curriculums, migrations.RunPython.noop),
    ]
